# Generated by Django 4.2.18 on 2025-02-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CofeeBeanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("certificate_valid", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CofeeMixEntryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Quantité en grammes"),
                ),
                (
                    "bean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRUDCofee.cofeebeanmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CofeeMixModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "beans",
                    models.ManyToManyField(
                        through="CRUDCofee.CofeeMixEntryModel",
                        to="CRUDCofee.cofeebeanmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cofeemixentrymodel",
            name="mix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CRUDCofee.cofeemixmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cofeemixentrymodel",
            unique_together={("mix", "bean")},
        ),
    ]
